### ISSUE TITLE
Implementación de hadware

### ISSUE THREAD

**Issue by Magno-Luque** [Magno-Luque/PI1#6]

**Comment by Marlith08** [comment]
Primeramente se realizará las impresiones 3D de los componentes que faltan.

- [ ] Impresión 3D
     -   [ ] Tapa del tubo del sensor CO2
     -   [ ] Integración a la caja principal
     -   [ ] Caja de sensores
     
Una vez contada con todos los componentes procedemos a integrar teniendo en cuenta la parte principal y la parte de recepción de datos.

> Integración de Piezas

- [ ] Tapa del tubo principal que contiene el sensor CO2
- [ ] Caja de sensores (Esta caja contará con los sensores que irán incrustados en la tierra) para que este completado debe de contener los siguientes componentes:

     - [ ] Sensor de humedad y temperatura
     - [ ] Sensor de ph
     - [ ] Switch
     - [ ] NRF 24L01
     - [ ] PCB
     - [ ] Batería 9V
     - [ ] Arduino nano
       
- [x] Caja principal (Esta caja servirá como recepción de datos mediante el ESP32 y lo cual a través de wife enviará los datos para que se muestre en la aplicación), para que esté completo tiene que contener los siguientes componentes:

     - [x] Batería 9V
     - [x] ESP32
     - [x] NRF 24L01
       
- [x] Tubo parte superior (ventilador)  (Este componente servirá para que el C02 previamente guardado sea expulsado)
     - [x] Soporte del CO2
     
- [x] Tubo parte inferior (entrada del CO2) (mediante este tubo ingresará el CO2 lo cual será captado por el sensor de CO2)

- [ ] Integración a caja principal (es una pieza que sirve como un soporte y una unión entre la caja de sensores y el tubo principal)
